Importing Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Importing the dataset

In [ ]:
train_dataset = pd.read_csv('train.csv')

In [ ]:
train_dataset.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [ ]:
print(train_dataset)

     PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]


In [ ]:
X_train = train_dataset.drop(['Name'], axis = 1)

In [ ]:
X_train = X_train.drop(['Ticket'], axis = 1)
X_train = X_train.drop(['Embarked'], axis = 1)
X_train = X_train.drop(['Cabin'], axis = 1)

In [ ]:
print(X_train)

     PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare
0              1         0       3    male  22.0      1      0   7.2500
1              2         1       1  female  38.0      1      0  71.2833
2              3         1       3  female  26.0      0      0   7.9250
3              4         1       1  female  35.0      1      0  53.1000
4              5         0       3    male  35.0      0      0   8.0500
..           ...       ...     ...     ...   ...    ...    ...      ...
886          887         0       2    male  27.0      0      0  13.0000
887          888         1       1  female  19.0      0      0  30.0000
888          889         0       3  female   NaN      1      2  23.4500
889          890         1       1    male  26.0      0      0  30.0000
890          891         0       3    male  32.0      0      0   7.7500

[891 rows x 8 columns]


In [ ]:
X_train = X_train.drop(['Survived'], axis = 1)
X_train = X_train.iloc[:,:].values
print(X_train)

[[1 3 'male' ... 1 0 7.25]
 [2 1 'female' ... 1 0 71.2833]
 [3 3 'female' ... 0 0 7.925]
 ...
 [889 3 'female' ... 1 2 23.45]
 [890 1 'male' ... 0 0 30.0]
 [891 3 'male' ... 0 0 7.75]]


Categorical Encoding (One Hot Encoding)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers =[('encoder', OneHotEncoder(), [2])], remainder='passthrough')
X_train = ct.fit_transform(X_train)

In [ ]:
print(X_train[0])

[0.0 1.0 1 3 22.0 1 0 7.25]


In [ ]:
y_train = train_dataset.iloc[:,1].values
print(y_train)

[0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0
 1 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0
 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1
 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0
 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0
 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0
 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0
 1 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1
 1 1 1 1 1 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 1 0 1 0 0 1 0 0 0 

Handling Missing Vaues

In [ ]:
train_dataset.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
x = imputer.fit_transform(X_train[:,4].reshape(-1,1))
X_train[:,4] = x.reshape(891,)

In [ ]:
print(X_train)

[[0.0 1.0 1 ... 1 0 7.25]
 [1.0 0.0 2 ... 1 0 71.2833]
 [1.0 0.0 3 ... 0 0 7.925]
 ...
 [1.0 0.0 889 ... 1 2 23.45]
 [0.0 1.0 890 ... 0 0 30.0]
 [0.0 1.0 891 ... 0 0 7.75]]


For Test Cases

In [ ]:
test_dataset = pd.read_csv('test.csv')
print(test_dataset)

     PassengerId  Pclass  ... Cabin Embarked
0            892       3  ...   NaN        Q
1            893       3  ...   NaN        S
2            894       2  ...   NaN        Q
3            895       3  ...   NaN        S
4            896       3  ...   NaN        S
..           ...     ...  ...   ...      ...
413         1305       3  ...   NaN        S
414         1306       1  ...  C105        C
415         1307       3  ...   NaN        S
416         1308       3  ...   NaN        S
417         1309       3  ...   NaN        C

[418 rows x 11 columns]


In [ ]:
X_test = test_dataset.drop(['Name'], axis = 1)
X_test = X_test.drop(['Ticket'], axis = 1)
X_test = X_test.drop(['Embarked'], axis = 1)
X_test = X_test.drop(['Cabin'], axis = 1)

In [ ]:
print(X_test)

     PassengerId  Pclass     Sex   Age  SibSp  Parch      Fare
0            892       3    male  34.5      0      0    7.8292
1            893       3  female  47.0      1      0    7.0000
2            894       2    male  62.0      0      0    9.6875
3            895       3    male  27.0      0      0    8.6625
4            896       3  female  22.0      1      1   12.2875
..           ...     ...     ...   ...    ...    ...       ...
413         1305       3    male   NaN      0      0    8.0500
414         1306       1  female  39.0      0      0  108.9000
415         1307       3    male  38.5      0      0    7.2500
416         1308       3    male   NaN      0      0    8.0500
417         1309       3    male   NaN      1      1   22.3583

[418 rows x 7 columns]


In [ ]:
X_test.isnull().sum()

PassengerId     0
Pclass          0
Sex             0
Age            86
SibSp           0
Parch           0
Fare            1
dtype: int64

In [ ]:
X_test = X_test.iloc[:,:].values

In [ ]:
#ct = ColumnTransformer(transformers =[('encoder', OneHotEncoder(), [2])], remainder='passthrough')
X_test = ct.fit_transform(X_test)

In [ ]:
print(X_test[0])

[0.0 1.0 892 3 34.5 0 0 7.8292]


In [ ]:
x1 = imputer.fit_transform(X_test[:,4].reshape(-1,1))
x2 = imputer.fit_transform(X_test[:-1].reshape(-1,1))

In [ ]:
X_test[:,4] = x.reshape(418,)
X_test[:,-1] = x.reshape(418,)

In [ ]:
print(X_test)

[[0.0 1.0 892 ... 0 0 34.5]
 [1.0 0.0 893 ... 1 0 47.0]
 [0.0 1.0 894 ... 0 0 62.0]
 ...
 [0.0 1.0 1307 ... 0 0 38.5]
 [0.0 1.0 1308 ... 0 0 30.272590361445783]
 [0.0 1.0 1309 ... 1 1 30.272590361445783]]


In [ ]:
print(X_test[:,2][4])

896


Training Model on Training Set

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
y_pred = regressor.predict(X_test)
print(y_pred)

[ 9.32293520e-02  4.94379909e-01  1.13000684e-01  1.34211703e-01
  6.10871915e-01  2.05215450e-01  6.30477252e-01  2.46353693e-01
  6.96020727e-01  8.05895547e-02  1.16413185e-01  3.70364586e-01
  9.65354816e-01  6.44293393e-02  8.34328481e-01  7.90016230e-01
  2.60569475e-01  1.67114771e-01  6.03757100e-01  5.48704496e-01
  2.78090856e-01  2.12633337e-01  9.68967714e-01  4.86947513e-01
  7.68833892e-01 -3.43745100e-02  9.94133607e-01  1.59025387e-01
  3.97837689e-01  3.01607328e-02  1.35584622e-01  2.34339611e-01
  5.31046671e-01  5.45949173e-01  4.14739102e-01  1.80947296e-01
  6.29291907e-01  6.79932879e-01  1.45485832e-01  1.16706154e-01
  4.90171085e-02  4.56543600e-01  5.81618820e-02  8.00759662e-01
  8.45552098e-01  1.45556549e-01  3.76178443e-01  1.16786974e-01
  8.06910620e-01  5.58059793e-01  4.47662376e-01  3.04605239e-01
  7.48963797e-01  8.11933028e-01  2.86766311e-01  3.46277516e-02
  9.10649506e-02  1.45677778e-01  7.36759014e-02  9.38068286e-01
  1.89390265e-01  2.77404

In [ ]:
for i in range(0,len(y_pred)):
  if y_pred[i] < 0.5:
    y_pred[i]= int(0)
  else:
    y_pred[i] = int(1)
print(y_pred)

[0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 0.
 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0.
 1. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0.
 1. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 1. 0. 1. 0. 0. 0.
 1. 0. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 1. 0. 1.
 1. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 1. 0. 1. 1. 0. 1. 0. 0. 1. 0. 0.
 1. 1. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0.
 1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 1.
 1. 1. 0. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1.
 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0.
 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0.
 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0.

In [ ]:
new_set = []

In [ ]:
for i in range(0,len(y_pred)):
  n_list = []
  n_list.append(X_test[:,2][i])
  n_list.append(y_pred[i])
  new_set.append(n_list)
print(new_set)

[[892, 0.0], [893, 0.0], [894, 0.0], [895, 0.0], [896, 1.0], [897, 0.0], [898, 1.0], [899, 0.0], [900, 1.0], [901, 0.0], [902, 0.0], [903, 0.0], [904, 1.0], [905, 0.0], [906, 1.0], [907, 1.0], [908, 0.0], [909, 0.0], [910, 1.0], [911, 1.0], [912, 0.0], [913, 0.0], [914, 1.0], [915, 0.0], [916, 1.0], [917, 0.0], [918, 1.0], [919, 0.0], [920, 0.0], [921, 0.0], [922, 0.0], [923, 0.0], [924, 1.0], [925, 1.0], [926, 0.0], [927, 0.0], [928, 1.0], [929, 1.0], [930, 0.0], [931, 0.0], [932, 0.0], [933, 0.0], [934, 0.0], [935, 1.0], [936, 1.0], [937, 0.0], [938, 0.0], [939, 0.0], [940, 1.0], [941, 1.0], [942, 0.0], [943, 0.0], [944, 1.0], [945, 1.0], [946, 0.0], [947, 0.0], [948, 0.0], [949, 0.0], [950, 0.0], [951, 1.0], [952, 0.0], [953, 0.0], [954, 0.0], [955, 1.0], [956, 0.0], [957, 1.0], [958, 1.0], [959, 0.0], [960, 0.0], [961, 1.0], [962, 1.0], [963, 0.0], [964, 1.0], [965, 0.0], [966, 1.0], [967, 0.0], [968, 0.0], [969, 1.0], [970, 0.0], [971, 1.0], [972, 0.0], [973, 0.0], [974, 0.0], [97

In [ ]:
df = pd. DataFrame(new_set)

In [ ]:
print(df)

        0    1
0     892  0.0
1     893  0.0
2     894  0.0
3     895  0.0
4     896  1.0
..    ...  ...
413  1305  0.0
414  1306  1.0
415  1307  0.0
416  1308  0.0
417  1309  0.0

[418 rows x 2 columns]


In [ ]:
df.columns = ['PassengerId', 'Survived']

In [ ]:
df.head()

PassengerId  Survived
0          892       0.0
1          893       0.0
2          894       0.0
3          895       0.0
4          896       1.0

In [ ]:
type(y_pred[0])

numpy.float64

In [ ]:
df['Survived'] = df['Survived'].astype(int)

In [ ]:
df.to_csv ('predictions.csv', index = False, header=True)